.equ OWLED_PORT = PORTB
.equ OWLED_PIN = PINB
.equ OWLED_DDR = DDRB
.equ OWLED_DQ = PB1

.equ ALARM_PIN = PINB
.equ ALARM_DDR = DDRB
.equ ALARM_DQ = PB0

.equ RELAY_PORT = PORTC
.equ RELAY_DDR = DDRC
.equ RELAY_DQ = PC0


.equ KEY_READ_DELAY_COUNTS = 2
.equ LED_BLINK_DELAY_COUNTS = 2
.equ ALARM_TRIGGER_TIME = 64

.def STATE_KEY_FSM = R25
.equ KEY_FSM_NOKEY = 0
.equ KEY_FSM_DELAY = 1
.equ KEY_FSM_NOTRELEASED = 2

.def STATE_LED_FSM = R22
.equ LED_FSM_LIGHTS = 0
.equ LED_FSM_BLINKS_ONCE = 1
.equ LED_FSM_NOTLIGHTS = 2
.equ LED_FSM_SHUTS_ONCE = 3

.def STATE_ALARM_FSM = R21
.equ ALARM_FSM_ACTIVE = 0
.equ ALARM_FSM_INACTIVE = 1
.equ ALARM_FSM_TRIGGERED = 2

.def MSG_HIGH = R24
.def MSG_LOW = R23
.equ MSG_READ_VALID_KEY = 0
.equ MSG_READ_INVALID_KEY = 1

.equ VIRTUAL_TIMERS_COUNT = 4
.equ TIMER_KEY_DELAY = 0
.equ TIMER_LED_BLINK = 1
.equ TIMER_ALARM_TRIGGER = 2

